### ISSUE TITLE
Removing resources doesn't work as expected

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-ui-dotnet#191]
If I remove a resource that has been added to the project and then add another resource that brings back the removed resource with itself.

https://user-images.githubusercontent.com/2915573/127564065-e6803868-cfa6-4989-88e3-bfecd93a22b1.mp4

**Comment by MingboPeng** [comment]
Thanks @mostaphaRoudsari, this has been fixed in this PR https://github.com/ladybug-tools/honeybee-ui-dotnet/pull/193
